#! /usr/bin/env python3 
# -*- coding: utf-8

import os, subprocess, shutil, logging, sys
import pandas as pd
from Bio import SeqIO
import src.utilities as utils
import src.file_handling as filehandling
from src.argument_handling import parse_args, Shuttler
from src.database_handling import DataBaseHandler


__author__ = "Reilly Cooper"
__maintainer__ = "Reilly Cooper"
__email__ = "reilly.owen.cooper@gmail.com"
__description__ = "Refine and annotate MAGs"


def main():
    
    # Check dependencies
    dependencies_list = ['prodigal', 'hmmsearch', 'mmseqs']
    for executable in dependencies_list:
        filehandling.does_program_exist(executable)
        
    # Prep arguments
    args = parse_args(sys.argv[1:])
    
    # Initialize databases
    SWISSPROT_DB = os.path.join(os.path.dirname(__file__), "data/swissprot/swissprot")
    SCG_DB = os.path.join(os.path.dirname(__file__), "data/essential.hmm")
    
    if not os.path.exists(SWISSPROT_DB) or not os.path.exists(SCG_DB):
        dbs = DataBaseHandler()
        dbs.run()
    
    # Run toolkit
    shuttler = Shuttler(SWISSPROT_DB, SCG_DB)
    shuttler.route_args(args)
    

if __name__ == "__main__":
    main()